export const packageList = [
  {value: "ai", title: "Ant Design Icons"},
  {value: "bi", title: "Box Icons"},
  {value: "bs", title: "Bootstrap Icons"},
  {value: "ci", title: "Circum Icons"},
  {value: "cg", title: "css.gg"},
  {value: "di", title: "Dev icons"},
  {value: "fi", title: "Feather"},
  {value: "fa", title: "Font Awesome"},
  {value: "fc", title: "Flat Color Icons"},
  {value: "go", title: "Github Octicons icons"},
  {value: "gi", title: "Game Icons"},
  {value: "gr", title: "Grommet-Icons"},
  {value: "hi", title: "Heroicons"},
  {value: "hi2", title: "Heroicons 2"},
  {value: "im", title: "IcoMoon Free"},
  {value: "io", title: "Ionicons 4"},
  {value: "io5", title: "Ionicons 5"},
  {value: "mid", title: "Material Design icons"},
  {value: "rx", title: "Radix Icons"},
  {value: "ri", title: "Remix Icon"},
  {value: "sl", title: "Simple Line Icons"},
  {value: "si", title: "Simple Icons"},
  {value: "tb", title: "Tabler Icons"},
  {value: "ti", title: "Typicons"},
  {value: "tfi", title: "Themify Icons"},
  {value: "vsc", title: "VS Code Icons"},
  {value: "wi", title: "Weather Icons"},
];
